- name: return the RHSM HOSTNAME the system is registered to
  shell: awk -F'=' '/^hostname/ {print $2}' /etc/rhsm/rhsm.conf | awk '{gsub(" +","");print $0}'
  register: rhsm_hostname_check
  changed_when: False

- debug:
    msg: "{{ rhsm_hostname_check.stdout }}"

- name: set fact rhsm_host_match to true if it matches the system current RHSM HOST otherwise false
  set_fact:
    rhsm_host_match: "{{ true if rhsm_hostname|string == rhsm_hostname_check.stdout|string else false }}"

- name: setting rhsm_fix_registration status
  set_fact:
    rhsm_fix_registration: "{{ true if rhsm_host_match == false else false }}"
