- name: return the ORG the system is registered to
  shell: subscription-manager identity| awk -F':' '/org ID/ {print $2}'|tr -d " \t\n\r"
  register: rhsm_org_id_check
  changed_when: False
  ignore_errors: yes

- name: set fact org_id to true if it matches the system current org_id otherwise false
  set_fact:
    org_id: "{{ true if rhsm_org_id|string == rhsm_org_id_check.stdout|string else false }}"
    org_msg: "{{ 'in the right ORG' if rhsm_org_id|string == rhsm_org_id_check.stdout|string else 'system is not in the right org' }}"

- name: report the org the system is in
  debug:
    msg: "The {{ inventory_hostname }} is {{ org_msg }} with ORG ID {{ rhsm_org_id }}."

- name: check if system is registered to the correct RHSM host
  command: grep -xq 'hostname = {{ rhsm_hostname }}' /etc/rhsm/rhsm.conf
  register: rhsm_hostname_check
  ignore_errors: yes
  check_mode: no
  changed_when: no

- name: setting system re-register status to true or false
  set_fact:
    reregister_system: true
    register_system_msg:
  when: (org_id == false) or (rhsm_hostname_check.rc == 0)
