- name: return the RHSM HOSTNAME the system is registered to
  shell: awk -F'=' '/^hostname/ {print $2}' /etc/rhsm/rhsm.conf | awk '{gsub(" +","");print $0}'
  register: rhsm_hostname_check
  changed_when: False

- name: report which RHSM the system is registered to
  debug:
    msg: "The {{ inventory_hostname }} is registered to {{ rhsm_hostname_check.stdout }}."

- name: set fact rhsm_host_is_correct to true if it matches the system current RHSM HOST otherwise false
  set_fact:
    rhsm_host_is_correct: "{{ true if rhsm_hostname|string == rhsm_hostname_check.stdout|string else false }}"

- name: setting rhsm_fix_registration status
  set_fact:
    fix_registration: true
  when: rhsm_host_is_correct == false
