- name: return the ORG the system is registered to
  shell: subscription-manager identity| awk -F':' '/org ID/ {print $2}'|sed -e 's/^[ \t]*//'
  register: rhsm_org_id_check
  changed_when: False
  ignore_errors: yes

- name: set fact org_id to true if it matches the system current org_id otherwise false
  set_fact:
    org_id: "{{ true if rhsm_org_id|string == rhsm_org_id_check.stdout|string else false }}"
    org_msg: "{{ 'in the right ORG' if rhsm_org_id|string == rhsm_org_id_check.stdout|string else 'system is not in the right org' }}"

- name: check if system is registered to the correct RHSM host
  command: grep -xq 'hostname = {{ rhsm_hostname }}' /etc/rhsm/rhsm.conf
  register: rhsm_hostname_check
  ignore_errors: yes
  check_mode: no
  changed_when: no

- name: setting system re-register status to true or false
  set_fact:
    reregister_system: true
    register_system_msg:
  when: (org_id == false) or (rhsm_hostname_check.rc != 0)

- name: setting rhsm_fix_registration to true because the current ORG Id {{ org_msg }} does not match the requested {{ rhsm_org_id }}
  set_fact:
    fix_registration: true
  when: org_id == false or rhsm_hostname_check.rc != 0 