---
# tasks file for swygue-redhat-subscription
- name: ensure subscription-manager is installed
  package:
    name: subscription-manager
    state: present

- name: check if system is already registered
  command: subscription-manager refresh
  register: is_system_registered
  failed_when: False
  changed_when: False

- name: declare fact system_registered true if status is registered
  set_fact:
    system_registered: "{{ true if is_system_registered.rc==0 else false }}"

- name: declare fact remove_system_registration if rhsm_unregister is set
  set_fact:
    remove_system_registration: "{{ true if rhsm_unregister == true else false }}"

- name: check system if system is in the right ORG
  include_tasks: check_org.yml
  when: system_registered == true and rhsm_org_id != ""

- name: check system if system consuming the right content view
  include_tasks: check_cv.yml
  when: system_registered == true and rhsm_content_view != ""

- name: check system if system is registered to the correct RHSM host
  include_tasks: check_rhsm_hostname.yml
  when: system_registered == true and rhsm_hostname != ""

- name: UNREGISTER|remove system rhsm registration if subscription is not current or rhsm ORG id does not match the systems current registered ORG id
  include_tasks: unregister.yml
  when: ( (remove_system_registration == true) and 
          (system_registered == true) or
          ( fix_registration == true ))

- name: REGISTER|register system to RHSM
  include_tasks: register.yml
  when: ( (system_registered != true) and 
          (remove_system_registration != true) or 
          (fix_registration == true))

# TODO: commented out for now as this needs to be updated
# Since their could be multiple pool, it should check for
# each pool and remove pool not needed or attach pool needed
#- name: ATTACH POOL| ensure system is attached to correct pool
#  include_tasks: pools.yml
#  when: (system_registered == true and rhsm_pool|trim != "")

- name: REPOS| enable system repositories
  include_tasks: repos.yml
  when: (system_registered == true and rhsm_repos|trim != "" )
