---
# tasks file for swygue-redhat-subscription
- name: ensure subscription-manager is installed
  package:
    name: subscription-manager
    state: present

- name: check if system is already registered
  command: subscription-manager refresh
  register: is_system_registered
  failed_when: False
  changed_when: False

- name: declare fact system_registered true if status is registered
  set_fact:
    system_registered: "{{ true if is_system_registered.rc==0 else false }}"

- name: declare fact unregistered if rhsm_unregister is set
  set_fact:
    unregister_system: "{{ true if rhsm_unregister == true else false }}"

- name: check system if system is in the right ORG
  include_tasks: check_org.yml
  when: system_registered == true and rhsm_org_id != ""

- name: check system if system consuming the right content view
  include_tasks: check_cv.yml
  when: system_registered == true and rhsm_content_view != ""

- name: UNREGISTER|remove system rhsm registration if subscription is not current or rhsm ORG id does not match the systems current registered ORG id
  include_tasks: unregister.yml
  when: (unregister_system == true and system_registered == true) or
        ( reregister_system == true )
#        ((unregister_system != true) and (system_registered == true and org_id != true))

- name: REGISTER|register system to RHSM
  include_tasks: register.yml
  when: (system_registered != true) and (unregister_system != true)

# TODO: commented out for now as this needs to be updated
# Since their could be multiple pool, it should check for
# each pool and remove pool not needed or attach pool needed
#- name: ATTACH POOL| ensure system is attached to correct pool
#  include_tasks: pools.yml
#  when: (system_registered == true and rhsm_pool|trim != "")

- name: REPOS| enable system repositories
  include_tasks: repos.yml
  when: (system_registered == true and rhsm_repos|trim != "" )
