---
# TODO: Add task to update the ORG a update belong to before registering
#       Assuming host already exists.

- name: clean out existing subscription certificate
  shell: subscription-manager clean
  register: rhsm_clean
  changed_when: False
  ignore_errors: yes
  tags: [register]

- name: include check_katello_ca.yml
  include_tasks: check_katello_ca.yml
  tags: [register, katello_ca]
  when: rhsm_is_satellite

- name: install the katello consumer rpm
  package:
    name: "http://{{ rhsm_hostname }}/pub/{{ rhsm_katello_ca_consumer_rpm }}"
    state: present
  when: katello_ca_installed|default(false)|bool == false and rhsm_is_satellite

- name: Register to RHSM using activation key
  redhat_subscription:
    state: present
    activationkey: "{{ rhsm_activationkey }}"
    server_hostname: "{{ rhsm_hostname|default(null) }}"
    org_id: "{{ rhsm_org_id }}"
    force_register: True
  register: is_registered_actkey
  when: use_activation_key and not use_system_identity
  failed_when: "'The system has been registered with ID' not in is_registered_actkey.stdout"

# This has not been tested againist Satellite
- name: Register system using rhsm_identity
  redhat_subscription:
    state: present
    activationkey: "{{ rhsm_activationkey }}"
    server_hostname: "{{ rhsm_hostname|default(null) }}"
    org_id: "{{ rhsm_org_id }}"
    use_system_identity: "{{ rhsm_identity }}"
  register: is_registered_use_system_identity
  when: use_system_identity and not use_activation_key
  failed_when: "'The system has been registered with ID' not in is_registered_use_system_identity.stdout"

- name: Register system using rhsm_user and rhsm_password
  redhat_subscription:
    state: present
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_pass }}"
    server_hostname: "{{ rhsm_hostname }}"
    auto_attach: true
    force_register: yes
    org_id: "{{ rhsm_org_id|default(null) }}"
  register: is_registered_rhsm_user
  when: not use_system_identity and not use_activation_key
  #failed_when: "'The system has been registered with ID' not in is_registered_use_system_identity.stdout"

- name: refresh subscriptions
  shell: subscription-manager refresh
  register: rhsm_refresh
  changed_when: False
  when: is_registered_rhsm_user is changed

# These should be removed as they are not current used
- name: declare system registered with consumer id
  set_fact:
    registration_use_system_identity: true
    registration_message: "System successfully registered with consumer id"
  when: ("'System successfully registered to' in is_registered_use_system_identity")

- name: declare system registered with activationkey
  set_fact:
    registration_activation_key: true
    registration_message: "System successfully registered with activation key"
  when: ("'System successfully registered to' in is_registered_actkey")
